#!/bin/sh
alias j='z'
alias f='zi'
#alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias lg='lazygit'
alias ld='lazydocker'
alias ht='sudo htop'
alias tree='tree -C'
alias ls='ls -al --color'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Tmux shortcuts
alias tms='active_tmux'

# Neovim shortcuts.
alias neoconfig="nvim ~/dot-files/nvim/.config/nvim/init.lua"
alias neopacker="nvim ~/dot-files/nvim/.config/nvim/lua/core/packer.lua"

# numo AWS
alias work='numowork'
alias awswhoami='okta aws sts get-caller-identity'
alias tfinit='_tf_init && okta terraform init -backend=true -backend-config=backend-${AWS_PROFILE}.config -var-file=vars-${AWS_PROFILE}.tfvars'
alias tfapply='okta terraform apply -var-file=vars-${AWS_PROFILE}.tfvars ${@} ' 
alias tfplan='okta terraform plan -var-file=vars-${AWS_PROFILE}.tfvars ${@} '
alias tfi='okta terraform init'
alias tfa='okta terraform apply'
alias tfp='okta terraform plan'
alias tfd='okta terraform destroy'

# nano
alias nano='/opt/homebrew/bin/nano'
