#!/bin/sh

# Environment variables set everywhere
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.fnm:$PATH

export COLORTERM=truecolor
export EDITOR=“code”
export TERMINAL=“terminal”
export BROWSER="safari"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/usr/local/vimr/bin:$PATH"
# export TERM=xterm

# Lazy Docker
export DOCKER_HOST=ssh://justin@192.168.1.145

# AWS
export AWS_PROFILE=mvc-1-app-2

# Terraform Logs
# export TF_LOG_CORE=TRACE
# export TF_LOG_PROVIDER=TRACE
# export TF_LOG_PATH=~/Library/Logs/terraform.log
