#!/bin/sh

# Environment variables set everywhere
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.fnm:$PATH

export COLORTERM=truecolor
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="safari"
export PATH="/opt/homebrew/bin:$PATH"
# export TERM=xterm

# AWS
export AWS_PROFILE=mvc-1-app-2

# FZF Theme
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
 --color=fg:#fbf1c7,bg:#3c3836,hl:#458588
 --color=fg+:#fbf1c7,bg+:#3c3836,hl+:#83a598
 --color=info:#d79921,prompt:#9d0006,pointer:#83a598
 --color=marker:#8ec07c,spinner:#b16286,header:#689d6a'
