#!/bin/sh

# Environment variables set everywhere
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.fnm:$PATH

export COLORTERM=truecolor
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="safari"
export PATH="/opt/homebrew/bin:$PATH"
# export TERM=xterm

# AWS
export AWS_PROFILE=mvc-1-app-2

# FZF Theme
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' 
  --color=fg:#3e3e3e,bg:#f5f5f5,hl:#0e73a4 
  --color=fg+:#3e3e3e,bg+:#f5f5f5,hl+:#0e73a4
  --color=info:#f6bb63,prompt:#ca1243,pointer:#85889b
  --color=marker:#33aa34,spinner:#ffa29f,header:#ca1243'
