-- Loading the plugins
require('plugins.devicons.lua')
require('plugins.indentline.lua')
require('plugins.lualine.lua')
require('plugins.nvimcmp.lua')
require('plugins.telescope.lua')
require('plugins.lsp.init')
require('plugins.treesitter.lua')
require('plugins.autocommands.lua')
require('plugins.autopairs.lua')
-- require('plugins.lazygit.lua')
require('plugins.project.lua')
require('plugins.highlights.init')
require('plugins.nvimtree.lua')
require('plugins.alpha.lua')
require('plugins.symbols-outlines.lua')
